2.2 Toolkit changes broke many modes, inc Android
Stub out the setIcon(Frame f) method on Toolkit so that the four or
five modes that use it don't NoSuchMethodError on them.